[package]
name = "arbitor"
version = "0.0.1"
edition = "2018"

[lib]
name = "arbitor"
path = "src/lib.rs"

[[bin]]
name = "arbitor"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
